application: ff8-gf-corral
version: 1
runtime: php
api_version: 1

handlers:
- url: /assets
  static_dir: web/public/assets
- url: /bootstrap
  static_dir: web/public/bootstrap

- url: /.*
  script: web/public/index.php
